myproject/myproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from boards import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
	url(r'^boards/(?P<pk>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),

]

myproject/boards/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class Board(models.Model):
	name = models.CharField(max_length=30, unique=True)
	description = models.CharField(max_length=100)

class Topic(models.Model):
	subject = models.CharField(max_length=255)
	last_updated = models.DateTimeField(auto_now_add=True)
	board = models.ForeignKey(Board, related_name='topics')
	starter = models.ForeignKey(User, related_name='topics')

class Post(models.Model):
	message = models.TextField(max_length=4000)
	topic = models.ForeignKey(Topic, related_name='posts')
	created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
	updated_at = models.DateTimeField(null=True)
	created_by = models.ForeignKey(User, related_name='posts')
	updated_by = models.ForeignKey(User, null=True, related_name='+')

myproject/boards/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
# Create your views here.
# from django.utils.datastructures import MultiValueDictKeyError
from .models import Board, Topic, Post
from django.http import Http404

def home(request):
	boards = Board.objects.all()
	return render(request, 'home.html', {'boards': boards})

def board_topics(request, pk):
	try:
		board = Board.objects.get(pk=pk)
	except Board.DoesNotExist:
		raise Http404
	return render(request, 'topics.html', {'board': board})

def new_topic(request, pk):
	board = get_object_or_404(Board, pk=pk)

	# try:
 #    	is_private = request.POST['is_private']
	# except MultiValueDictKeyError:
 #    	is_private = False

	if request.method =='POST':
		subject = request.POST['Subject']
		message = request.POST['message']
		# print subject
		# print message
		user = User.objects.first()
		topic = Topic.objects.create(
			subject=subject, 
			board=board, 
			starter=user)

		post = POST.objects.create(
			message=message, 
			topic=topic, 
			created_by=user)

		return redirect('board_topics', pk=board.pk)

	return render(request, 'new_topic.html', {'board': board})

myproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Boards{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
        </div>
    </nav>
    <div class="container">
        <ol class="breadcrumb my-4">
            {% block breadcrumb %} {% endblock %}
        </ol>
        {% block content %} {% endblock %}
    </div>
</body>

</html>

myproject/templates/home.html
{% extends 'base.html' %} 

{% block breadcrumb %}
<li class="breadcrumb-item active">Boards</li>

{% endblock %} {% block content %}

<table class="table">
    <thead class="thead-inverse">
        <tr>
            <th>Board</th>
            <th>Posts</th>
            <th>Topics</th>
            <th>Last Post</th>
        </tr>
    </thead>
    <tbody>
        {% for board in boards %}
        <tr>
            <td>
                <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
                <small class="text-muted d-block">{{ board.description }}</small>
            </td>
            <td class="align-middle">0</td>
            <td class="align-middle">0</td>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

myproject/templates/new_topic.html
{% extends 'base.html' %} 

{% block title %}Start a New Topic{% endblock %} 

{% block breadcrumb %}

<li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
<li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
<li class="breadcrumb-item active">New topic</li>

{% endblock %}



{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_subject">Subject</label>
        <input type="text" class="form-control" id="id_subject" name="subject">
    </div>
    <div class="form-group">
        <label for="id_message">Message</label>
        <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}

myproject/templates/topics.html
{% extends 'base.html' %} 

{% block title %} 
	{{ board.name }} - {{ block.super }} 
{% endblock %} 


{% block breadcrumb %}
	<li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
	<li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %} 

{% block content %}
<!-- just leaving it empty for now. we will add core heresoon. -->
{% endblock %}